name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v2

      - name: Gerar a cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: MatheusFreitasGabriel  # Substitua pelo seu username
          outputs: dist/snake.svg

      - name: Adicionar cobrinha ao README
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
