name: Generate Animation

on:
  schedule:
    - cron: "0 */24 * * *"  # Executa automaticamente a cada 24 horas
  workflow_dispatch:  # Permite rodar o workflow manualmente
  push:
    branches:
      - master  # Executa o workflow sempre que houver push na branch master

jobs:
  generate:
    permissions:
      contents: write  # Permite que o GitHub Actions escreva no repositório
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Gera a animação da cobrinha com base nas contribuições do usuário no GitHub
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.actor }}  # Usa o nome de usuário do autor do repositório
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Envia o arquivo gerado para a branch "output"
      - name: Push GitHub Contribution Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Envia para a branch "output"
          build_dir: dist  # Diretório onde o arquivo SVG foi gerado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usando o token do GitHub para autenticação
